name: acceptance-tests-pr

on:
  pull_request:
    branches:
    - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v1

    - name: Run acceptance tests
      run: make github-actions-ci

    - uses: actions/upload-artifact@master
      name: Upload test report
      with:
        name: helm-acceptance-testing-report-${{ github.sha }}
        path: acceptance-testing-reports/${{ github.sha }}/
      if: always()
